### ISSUE TITLE
[Bug]  does not do anything

### ISSUE THREAD

**Issue by joethei** [mgmeyers/obsidian-embedded-note-titles#15]
Obsidian version: 0.12.19

Whenever I open a note the following error shows up in the console and nothing happens in the note.
```
Uncaught DOMException: Failed to execute 'matches' on 'Element': The provided selector is empty.
    at getMatchedCSSRules (eval at <anonymous> (app://obsidian.md/app.js:1:1287967), <anonymous>:129:25)
    at getRefSizing (eval at <anonymous> (app://obsidian.md/app.js:1:1287967), <anonymous>:164:19)
    at HeadingsManager.getPreviewSizerStyles (eval at <anonymous> (app://obsidian.md/app.js:1:1287967), <anonymous>:214:36)
    at HeadingsManager.createHeading (eval at <anonymous> (app://obsidian.md/app.js:1:1287967), <anonymous>:292:18)
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1287967), <anonymous>:343:22)
    at t.iterateLeaves (app://obsidian.md/app.js:1:1276816)
    at t.iterateLeaves (app://obsidian.md/app.js:1:1276914)
    at t.iterateRootLeaves (app://obsidian.md/app.js:1:1276999)
    at HeadingsManager.createHeadings (eval at <anonymous> (app://obsidian.md/app.js:1:1287967), <anonymous>:340:23)
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1287967), <anonymous>:368:38)
```

**Comment by mgmeyers** [comment]
@joethei I'm unable to reproduce this issue. Can you update the plugin and see if you still encounter this?

**Comment by joethei** [comment]
Yes I can still reproduce this issue in my main vault(even with all other plugins and snippets disabled), but not my plugin dev vault.
But only in Reading mode, it works in LivePreview & Editing Mode, but still throws that error, but now it appears twice.

**Comment by mgmeyers** [comment]
Ok, I added a check that should hopefully fix this. Could you update and test it out?

**Comment by joethei** [comment]
yes that seems to fix it, everything works now, thank you.

The one plugin I found this does not play nice with is Banners, 
I would guess because both put content at the same location.
